<%-- 
    Document   : terms
    Created on : 27 Aug, 2019, 11:10:48 PM
    Author     : yoyoa
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <header>
            <jsp:include page="header.jsp"/>
        </header>
        
        
        ABAP INSURANCE SERVICES LLC
Terms of Use
Welcome and thank you for your interest in ABAP, Inc. (“ABAP”) and its affiliates ABAP Insurance MMIS LLC (“MMIS”) and ABAP Insurance Company (“MIC”, and collectively with MMIS and ABAP, the (“Company”). This website and any parent or child sites (collectively, the “Site”) allows users to access information and obtain quotes and coverage, and change or cancel such coverage, for certain insurance products issued by MIC and serviced by MMIS (excluding claims which are handled by MIC or a third-party).  ABAP has also developed and released , software applications for mobile phones (the “Apps”) (the Site and the Apps, together with the other online features and services provided by the Company, as applicable, are collectively referred to as the “Service”).  The terms of any insurance policy or claim are governed by your applicable insurance policy, and any conflict between these Terms of Use, Terms and Conditions for the Pulse Device, or Electronic Terms of Delivery policy are governed by the applicable policy and applicable law.

The Privacy Policy, Terms and Conditions for the Pulse Device, or Electronic Terms of Delivery policy are each incorporated into these Terms of Use.  Any conflict between the listed policies and these Terms of Use will be governed by the applicable policy.

1. ACCEPTANCE OF THE TERMS.
Please carefully read the following terms of use and all other rules and guidelines that we may communicate to you from time to time through the Service, including the Privacy Policy which are incorporated herein by reference (collectively, the “Terms”), as these terms create a binding legal contract between you and the Company. By accessing, using or availing yourself of the Service in any manner, you (“You”, or “User”) acknowledge that you have read, understood, and agree to be bound by and comply with the Terms. If at any time you do not agree to these Terms, you should immediately terminate any and all use of the Service. To the extent that you download and use any separate software applications from the Company (whether directly through the Service or made available to you through a third party application marketplace), your use of such application will be governed by the terms of the applicable end user license which will be incorporated into and made a part of these Terms.

2. ACCESSING THE SERVICE.
Eligibility.
You must be an individual at least 16 years old to use the Service. Certain plans or activities presented through the Service may have other age restrictions. By using the Service, you represent that you are at least the minimum required age (in no case less than 13 years old) or and in any case that you are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms. Further, by using or registering for the Service, you agree to abide by and comply with these Terms, and you acknowledge that you are accepting the benefit of the Service, subject to these Terms.

Access.
Company grants you permission to access and use the Service as set forth in these Terms and consistent with the intended features of the Service, provided that: (i) you use the Service solely for your personal, private, noncommercial purposes; (ii) you do not reproduce, modify, publicly display, publicly perform, or distribute any part of the Service, including any materials obtained from or included within the Service; and (iii) you do not engage in any of the prohibited uses described below.

3. ACCOUNT INFORMATION & RESPONSIBILITIES OF REGISTERED USERS.
Account Information.
In order to access some features of the Service, you will have to create an account. You hereby represent and warrant that the information you provide to Company upon registration (including information provided through your linked Facebook account, as applicable, or other third party Linked Accounts, as defined below), and at all other times, will be true, accurate, current, and complete. You also hereby represent and warrant that you will ensure that this information is kept accurate and up-to-date at all times.

Password.
As a registered User, you will have login information, including a username and password. Your account is personal to you, and you may not share your account information with, or allow access to your account by, any third party. As you will be responsible for all activity that occurs under your access credentials, you should preserve the confidentiality of your username and password. If you have any reason to believe that your account information has been compromised or that your account has been accessed by a third party, you agree to immediately notify Company by submitting a case here. You are solely responsible for your own losses or losses incurred by Company and others (including other users) due to any unauthorized use of your account that occur prior to notifying Company that your account was compromised.

Location Information.
In the event that you purchase insurance coverage through MMIS, you will be required to connect a wireless enabled telematics device to your covered vehicle(s). The device is capable of collecting and communicating back a variety of diagnostic information about your vehicle and your trips, including speed, heading, acceleration, altitude, odometer and location information. This information is used to enable features of the Service, including displaying maps of your trips.  See Terms and Conditions for the Pulse Device for more information on the Pulse Device.

4. OWNERSHIP; PROPRIETARY RIGHTS.
The Service is owned and operated by Company. The visual interfaces, graphics, design, compilation, information, computer code, products, software (including any downloadable software), services, and all other elements of the Service provided by Company (“Site Content”) are protected by United States copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. All Site Content is the copyrighted property of Company or its subsidiaries or affiliated companies and/or third parties, except for User Content, to which you retain your copyrights. You agree and understand that Site Content may include Third Party Content, as set forth in further detail in Section 6, below. All trademarks, service marks, and trade names are proprietary to Company or its affiliates and/or third parties. You agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Site Content, and nothing herein shall be interpreted to grant you any right or license under any intellectual property rights of Company or any third party.

5. LINKED ACCOUNTS AND SOCIAL NETWORKING SITES.
Company may, now or in the future, allow you to link your account(s) on the Service to your accounts on third party services, such as social networking sites (“Linked Accounts”). If you link your account on the Service to a Linked Account, you are authorizing Company to store and use your access credentials to access your Linked Account on your behalf as your agent to integrate your experience with the Service with content, information, and features available through such Linked Account. This may include importing the contacts, preferences, interests or “likes” of the Linked Account, and/or pushing updates regarding your use of the Service out to your Linked Accounts. Linking, accessing or using a third party service through the Service in this manner may be subject to additional terms established by the applicable third party, and it is your sole responsibility to comply with such third party terms.

6. THIRD PARTY CONTENT.
General.
Company may contain or display through the MMIS various information, and other materials or content from third parties, including User Content (“Third Party Materials”). The display on or through the website and MMIS of such Third Party Materials does not in any way imply, suggest, or constitute any sponsorship, endorsement, or approval of Company by any such third party or any affiliation between any such third party and Company. Furthermore, in using and accessing the Service, you agree that Company is in no way responsible for the accuracy, timeliness, or completeness of Third Party Materials. Company’s display of specific Third Party Materials does not suggest a recommendation by Company of the third party or any products, plans or service offered. Your interaction with any third party accessed through the Service (whether online or offline) is at your own risk, and Company will have no liability with respect to the acts, omissions, errors, representations, warranties, breaches or negligence of any such third party or for any personal injuries, death, property damage, or other damages or expenses resulting from your interactions with the third party.

Third Party Links and References.
The Service may contain references or links to third-party materials and services not controlled by Company or its suppliers or licensors. Company provides such information and links as a convenience to you and should not be considered endorsements or recommendations of such sites or any content, products or information offered on such sites. You acknowledge and agree that Company is not responsible for any aspect of the information or content contained in any third party materials or on any third party sites accessible or linked from the Service.

Google Maps.
Google Maps presented to you through the Service are powered by Google. Your use of such Google Maps is subject to the Google Maps Terms of Service, available online at https://developers.google.com/readme/terms, and by using the Service, you are agreeing to be bound by such terms.

7. USER CONTENT.
General.
The Service may now or in the future provide allow you and other users to submit, post, and share content such as text, photos, audiovisual content, and other media content (“User Content”).

Access and Responsibility.
While Company may provide certain tools to aid you in configuring access by others to your User Content, Company cannot guarantee any anonymity or confidentiality with respect to any User Content, and strongly recommends that you think carefully and use good judgment about what you submit to or make available through the Service. You understand that all User Content is the sole responsibility of the person who generated such User Content. This means that you, and not Company, are entirely responsible for User Content that you make available through the Service.

License Grant by You to Company.
You retain all of your ownership rights in original aspects your User Content. By providing User Content to Company you hereby grant Company and its affiliates, sublicensees, partners, designees, and assignees of the Service (collectively, the “Company Licensees”) a non-exclusive, fully paid-up, royalty-free, perpetual, irrevocable, sublicensable, transferable, worldwide license, without obligation, to use, reproduce, distribute, modify, adapt, publicly display, publicly perform, and otherwise exploit your User Content and derivatives thereof in connection with the Service and Company’s (and its successors’) business, including, without limitation, for marketing, promoting, and redistributing part or all of the Service (and derivative works thereof), in any media formats and through any media channels now known or hereafter discovered or developed.

User Content Representations and Warranties.
You are solely responsible for your own User Content and the consequences of posting or publishing it. In connection with User Content, you affirm, represent, and warrant that: (i) you own, or have the necessary licenses, rights, consents, and permissions to use and authorize Company to use all patent, trademark, copyright, or other proprietary rights in and to any and all User Content to enable the use of User Content in the manner contemplated by these Terms, and to grant the rights and license set forth herein, and (ii) your User Content, Company’s or any Company Licensee’s use of such User Content pursuant to these Terms, and Company’s or any Company Licensee’s exercise of the license rights set forth above, do not and will not: (a) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, or any other intellectual property or proprietary right; (b) slander, defame, libel, or invade the right of privacy, publicity of any other person; (c) violate any applicable law or regulation, or constitute any false or misleading advertising or unfair business practice; or (d) require obtaining a license from or paying royalties to any third party for the exercise of any rights granted in these Terms.

No Obligation to Publish.
Company makes no representations that it will publish or make available any User Content on the Service, and reserves the right, in its sole discretion, to reject or remove any User Content at any time with or without notice. Without limiting the generality of the preceding sentence, Company complies with the Digital Millennium Copyright Act, and will remove User Content upon receipt of a compliant takedown notice (see Section 10 titled “Digital Millennium Copyright Act”, below).

8. CONTENT DISCLAIMER.
YOU UNDERSTAND THAT WHEN USING THE SERVICE, YOU WILL BE EXPOSED TO USER CONTENT AND THIRD PARTY CONTENT FROM A VARIETY OF SOURCES, AND THAT COMPANY IS NOT RESPONSIBLE FOR THE ACCURACY, INTEGRITY, QUALITY, LEGALITY, USEFULNESS, SAFETY, OR INTELLECTUAL PROPERTY RIGHTS OF OR RELATING TO SUCH USER CONTENT OR THIRD PARTY CONTENT. YOU FURTHER UNDERSTAND AND ACKNOWLEDGE THAT YOU MAY BE EXPOSED TO USER CONTENT AND THIRD PARTY CONTENT THAT IS INACCURATE, OFFENSIVE, INDECENT, OR OBJECTIONABLE, AND YOU AGREE TO WAIVE, AND HEREBY DO WAIVE, ANY LEGAL OR EQUITABLE RIGHTS OR REMEDIES YOU HAVE OR MAY HAVE AGAINST COMPANY WITH RESPECT THERETO. COMPANY DOES NOT ENDORSE ANY USER CONTENT OR THIRD PARTY CONTENT, OR ANY OPINION, RECOMMENDATION, OR ADVICE EXPRESSED THEREIN. UNDER NO CIRCUMSTANCES WILL COMPANY BE LIABLE IN ANY WAY FOR OR IN CONNECTION WITH ANY USER CONTENT OR THIRD PARTY CONTENT.

9. MONITORING USER CONTENT; REMOVAL OF CONTENT.
Company does not control User Content and does not have any obligation to monitor such User Content for any purpose. Company may choose, in its sole discretion, to monitor, review, or otherwise access some or all User Content, but by doing so Company nonetheless assumes no responsibility for the User Content, no obligation to modify or remove any inappropriate User Content, or to monitor, review, or otherwise access other User Content, and Company assumes no responsibility for the conduct of the User submitting any User Content. You acknowledge that Company may or may not pre-screen User Content, but that Company and its designees shall have the right (but not the obligation) in their sole discretion to pre-screen, refuse, or remove any User Content that is available via the Service. Without limiting the foregoing, Company and its designees may, at any time and without prior notice, remove any User Content that in the sole judgment of Company violates these Terms or is otherwise objectionable, or for any other reason, with or without notice and with no liability of any kind. You agree that you must evaluate, and bear all risks associated with the use of any User Content or other Content, including any reliance on the accuracy, completeness, usefulness or legality of such User Content. You should exercise your independent discretion and judgment before downloading any other User Content.

10. DIGITAL MILLENNIUM COPYRIGHT ACT COMPLIANCE.
General.
Company respects the rights of copyright owners and expects its users to do the same. Therefore, as required by the Terms, infringing content may not be submitted to the Service or used in, whole or in part, in any User Content.

User Content.
If you upload User Content that contains any copyrighted work, including literary works, visual works, musical works, sound recordings, audiovisual works, or other work or any combination of the foregoing, then you must be the owner of such works or have all required rights, licenses, consents, and permissions to use such works on the Service and grant the rights granted herein. In addition to being grounds for removal of your User Content, termination of your account, and any other remedy Company may have against you, your failure to own or obtain such rights may subject you to civil and/or criminal liability, the damages for which can be significant.

Copyright Owner Rights
If you are a copyright owner or an agent thereof, and you believe any content submitted to and hosted on the Service infringes your copyrights, then you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA” ) by providing Company’s Designated Copyright Agent with the following information in writing:

(i) a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;

(ii) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the Service are covered by a single notification, a representative list of such works on the Service;

(iii) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Company to locate the material;

(iv) information reasonably sufficient to permit Company to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;

(v) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law (for example, “I am under the good faith belief that the use of the copyrighted content that is identified herein is not authorized by the copyright owner, its agent, or the law.”); and

(vi) a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed (for example, “I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or authorized to act on behalf of the copyright owner, of the copyright(s) that is/are allegedly infringed by the aforementioned content.”).

Please consult your legal counsel (or see 17 U.S.C. Section 512) to confirm these requirements and your compliance therewith. It is Company’s policy to respond to notices of alleged infringement that comply with the DMCA. In addition, Company will promptly terminate without notice the accounts of Users that are determined by Company to be “repeat infringers.” If Company receives more than three takedown notices regarding a User’s User Content, then that User will be considered a repeat infringer and their account will be terminated.

Designated Agent
Company’s Designated Copyright Agent to receive notifications and counter-notifications of claimed infringement can be reached as follows: Attention: Copyright Agent, ABAP, Inc. 690 Folsom Street Suite 200, San Francisco, CA 94107, or by electronic mail at copyright@metromile.com. For clarity, only DMCA notices should go to the Designated Copyright Agent. Any other feedback, comments, requests for technical support or other communications should be directed to Company customer service through this form. You acknowledge that if you fail to comply with all of the requirements of this section, your DMCA notice may not be valid. Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.

11. PROHIBITED USES OF SERVICE.
You agree not to use the Service or any aspect or feature thereof for any unlawful purpose or in any way that might harm, damage, or disparage any other party. Without limiting the proceeding sentence, you agree that you will not, do or attempt to:

Post, upload, publish, submit, or transmit any User Content that: (i) infringes, misappropriates or violates a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any person or entity; or (vii) promotes illegal or harmful activities or substances;
Use, display, mirror or frame the Service or any individual element within the Service, MMIS, MIC or MetrotMile’s name, any Company trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without a party’s express written consent;
Access, tamper with, or use non-public areas of the Site, MMIS, Company’s computer systems, or the technical delivery systems of Company’s providers;
Attempt to probe, scan, or test the vulnerability of any system or network or breach any security or authentication measures;
Avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by the Company or any of Company’s providers or any other third party including another user to protect the MMIS or Site Content;
Attempt to access or search the MMIS or Site Content or download Site Content from the MMIS through the use of any engine, software, tool, agent, device or mechanism including spiders, robots, crawlers, data mining tools or the like other than the software and/or search agents provided by Company or other generally available third-party web browsers;
Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation;
Use any meta tags or other hidden text or metadata utilizing a Company trademark, logo URL or product name without Company’s express written consent;
Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the MMIS or Site Content to send altered, deceptive or false source-identifying information;
Attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the MMIS or Site Content;
Copy, modify or create derivative works based on the Site Content and MMIS, other than your own User Site Content;
Interfere with, or attempt to interfere with, the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the MMIS;
Collect or store any personally identifiable information from the MMIS from other Users of the MMIS without their express permission;
Impersonate or misrepresent your affiliation with any person or entity;
Violate any applicable law or regulation;
Publish or distribute any Site Content or Third Party Site Content without the prior written consent of the Company; Access or use the Service for any commercial or business purpose, including without limitation for comparative or competitive research purposes;
Transmit or upload any material that contains viruses, Trojan horses, worms, time bombs, cancelbots, or any other harmful or deleterious software programs;
Encourage or enable any other individual to do any of the foregoing; or
Use the Service in any manner whatsoever that could lead to a violation of any federal, state or local laws, rules or regulations.
12. MODIFICATION OF THE TERMS.
Company reserves the right to update or modify the Terms at any time without prior notice, and such changes will be effective immediately upon being posted on the Site  and your use of the Site will be considered acceptance of the new terms. In the case of material changes to the Terms, Company will make reasonable efforts to notify you of the change, such as through sending an email to any address you may have used to register for an account, through a pop-up window on the Service, or other similar mechanism. We encourage you to review these Terms frequently to stay informed of the latest modifications.

13. TERMINATION.
By Company.
Company, in its sole discretion and for any reason or no reason, may terminate your account on the Service, disable your access to the Service (or any part thereof), discontinue the Service, or terminate any license or permission granted to you hereunder, at any time, with or without notice, including without limitation in connection with any termination of any insurance policy you may have with the Company. You agree that Company shall not be liable to you or any third-party for any such termination. Without limiting the generality of the foregoing, Company may terminate your account in cases of actual or suspected fraud, or violations of these Terms or other laws or regulations, and any suspected fraudulent, abusive, or illegal activity may be referred to appropriate law enforcement authorities. These remedies are in addition to any other remedies Company may have at law or in equity.

By You.
If you are dissatisfied with the Service, then please let us know by visiting https://www.metromile.com/help/contact. Your only remedy with respect to any dissatisfaction with (i) the Service, (ii) any of these Terms, (iii) any policy or practice of Company in operating the Service, or (iv) any content or information transmitted or made available through the Service, is to terminate your use of the Service. You may terminate only by discontinuing your insurance policy (and thus your account on the Service) by calling ABAP at 1-888-244-1702.

14. INDEMNITY.
You agree to indemnify and hold harmless Company and its parent, subsidiaries, affiliates or any related companies, licensors and suppliers, and their respective directors, officers, employees, agents, representatives, customers, and contractors, from all damages, injuries, liabilities, costs, fees and expenses (including, but not limited to, legal and accounting fees) arising from or in any way related to (i) your use or misuse of the Service (including your use or misuse of Third Party Materials); (ii) your User Content; (iii) your breach or other violation of these Terms including any representations, warranties and covenants herein; (iv) your violation of the rights of any other person or entity, including, but not limited to claims that any User Content infringes or violates any third party intellectual property rights. Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You may not settle any matter without the prior written consent from Company.

15. DISCLAIMERS.
THE SERVICE (INCLUDING, WITHOUT LIMITATION, THE SITE, SITE CONTENT, OR ANY OTHER PRODUCT, SERVICE OR INFORMATION PROVIDED BY COMPANY), USER CONTENT, THIRD-PARTY CONTENT, AND ANY OTHER SOFTWARE, SERVICES OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE SERVICE, ARE PROVIDED ON AN “AS IS”, “AS AVAILABLE”, “WITH ALL FAULTS” BASIS WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE.

TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ARISING FROM A COURSE OF DEALING, WITH RESPECT TO THE PRODUCTS OR SERVICES PROVIDED BY COMPANY.

16. LIMITATION OF LIABILITY.
IN NO EVENT WILL COMPANY, ITS OFFICERS OR DIRECTORS BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, SPECIAL OR OTHER CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH (I) YOUR USE OF THE SERVICE, SITE CONTENT, THIRD PARTY MATERIALS OR THE SITE; (II) THE USE OR ACCESS OF OR INABILITY TO USE OR ACCESS THE SERVICE OR ANY CONTENT; OR (III) PLANS MADE OR INFORMATION ACQUIRED THROUGH THE SERVICES, INCLUDING, WITHOUT LIMITATION, (I) ANY FEES OR COSTS ASSOCIATED WITH CANCELLED, INTERRUPTED OR DELAYED PLANS; (II) ANY FEES OR COSTS RESULTING FROM MISINFORMATION OR FAILURES IN COMMUNICATION; (III) AND ANY ACCIDENTS OR UNEXPECTED EVENTS OTHERWISE, WHETHER BASED IN TORT, CONTRACT OR OTHER LEGAL THEORY, EVEN IF COMPANY IS EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL COMPANY, ITS OFFICERS OR DIRECTORS BE LIABLE IN THE AGGREGATE FOR ANY DAMAGES INCURRED GREATER THAN FIVE HUNDRED DOLLARS ($500).

17. LIMITATIONS; BASIS OF THE BARGAIN.
APPLICABLE LAW MAY NOT ALLOW FOR THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, YOU AGREE THAT BECAUSE SUCH WARRANTY DISCLAIMERS AND LIMITATIONS OF LIABILITY REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND COMPANY, AND ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN YOU AND COMPANY, COMPANY’S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW. YOU UNDERSTAND AND AGREE THAT COMPANY WOULD NOT BE ABLE TO OFFER THE SERVICE TO YOU ON AN ECONOMICALLY FEASIBLE BASIS WITHOUT THESE LIMITATIONS.

18. DISPUTE RESOLUTION AND ARBITRATION.
Generally.
In the interest of resolving disputes between you and Company in the most expedient and cost effective manner, you and Company agree that any and all disputes arising in connection with this Agreement shall be resolved by binding arbitration. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Our agreement to arbitrate disputes includes, but is not limited to all claims arising out of or relating to any aspect of these Terms, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory, and regardless of whether the claims arise during or after the termination of these Terms. You understand and agree that, by entering into these Terms, you and Company are each waiving the right to a trial by jury or to participate in a class action.

Exceptions.
Notwithstanding subsection (A), we both agree that nothing herein shall be deemed to waive, preclude, or otherwise limit either of our right to (i) bring an individual action in small claims court, (ii) pursue enforcement actions through applicable federal, state, or local agencies where such actions are available, (iii) seek injunctive relief in a court of law, or (iv) to file suit in a court of law to address intellectual property infringement claims.

Arbitrator.
Any arbitration between you and Company will be governed by the Commercial Dispute Resolution Procedures and the Supplementary Procedures for Consumer Related Disputes (collectively, “AAA Rules”) of the American Arbitration Association (“AAA”), as modified by these Terms, and will be administered by the AAA. The AAA Rules and filing forms are available online at www.adr.org, by calling the AAA at 1-800-778-7879, or by contacting Company.

Notice; Process
A party who intends to seek arbitration must first send a written notice of the dispute to the other, by certified mail or Federal Express (signature required), or in the event that we do not have a physical address on file for you, by electronic mail (“Notice”). Company’s address for Notice is: ABAP, Inc. 690 Folsom Street Suite 200, San Francisco, CA 94107. The Notice must (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought (“Demand”). We agree to use good faith efforts to resolve the claim directly, but If we do not reach an agreement to do so within 30 days after the Notice is received, you or ABAP may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by you or ABAP shall not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any; provided that if our dispute is finally resolved through arbitration in your favor, ABAP shall pay you the greater of (i) the amount awarded by the arbitrator, if any, and (ii) the greatest amount offered by ABAP in settlement of the dispute prior to the arbitrator’s award.

Fees.
In the event that you commence arbitration in accordance with these Terms, Company will reimburse you for your payment of the filing fee, unless your claim is for greater than $10,000, in which case the payment of any fees shall be decided by the AAA Rules. Any arbitration hearings will take place at a location to be agreed upon in San Francisco County, California, provided that if the claim is for $10,000 or less, you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a non-appearance based telephonic hearing, or by an in-person hearing as established by the AAA Rules. If the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules. In such case, you agree to reimburse Company for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within 14 days of the arbitrator’s ruling on the merits.

No class actions.
YOU AND COMPANY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and Company agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding.

Modifications.
In the event that Company makes any future change to this arbitration provision (other than a change to the Company’s address for Notice), you may reject any such change by sending us written notice within 30 days of the change to Company’s address for Notice, in which case your account with Company shall be immediately terminated and this arbitration provision, as in effect immediately prior to the amendments you reject shall survive.

Enforceability.
If only Subsection F of this Section 18 or the entirety of this Section 18 is found to be unenforceable, then the entirety of this Section shall be null and void and, in such case, the parties agree that the exclusive jurisdiction and venue described elsewhere in Section 20 shall govern any action arising out of or related to these Terms.

19. NOTICES.
Company will provide you with notices hereunder as specified under “Delivery Process” in the Electronic Terms of Delivery policy.

20. MISCELLANEOUS.
These Terms, whether interpreted in a court of law or in arbitration, shall be governed by the laws of the State of California as they apply to agreements entered into and to be performed entirely within California by California residents, and without regard to conflict of law principles. To the extent that any arbitration, lawsuit or court proceeding is permitted hereunder, you and Company agree to submit to the personal and exclusive jurisdiction of the state courts and federal courts located within San Francisco County, California for the purpose of all such claims or disputes. This is the entire agreement between you and Company relating to the subject matter herein, and supersedes all previous communications, representations, understandings and agreements, either oral or written, between you and Company with respect to said subject matter. In the event any of the provisions of these Terms are held unenforceable or invalid by a court of competent jurisdiction, such provisions shall be deemed severed, and the remaining provisions thereof shall remain in full force and effect. The failure of Company to enforce, in any one or more instances, any of the provisions herein shall not be construed as a waiver of the prior or future performance of any such terms or conditions. You agree that no joint venture, partnership, employment, or agency relationship exists between you and Company as a result of these Terms or use of the Service. You further acknowledge that by submitting User Content, no confidential, fiduciary, contractually implied, or other relationship is created between you and Company other than pursuant to these Terms. The Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Company without restriction, including by operation of law, merger, or sale of all or substantially all of the assets to which this agreement pertains. Any assignment attempted to be made in violation of these Terms shall be void. The headings and captions in this Agreement are used for convenience only and are not to be considered in interpreting this Agreement.
        
      
    </body>
    <footer>
        <jsp:include page="footer.jsp"/>
    </footer>
</html>
